import type { MetadataRoute } from 'next'

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://adrexo.net'

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date()

  const routes: MetadataRoute.Sitemap = [
    { url: BASE_URL, lastModified, changeFrequency: 'weekly', priority: 1 },
    { url: `${BASE_URL}/street-marketing`, lastModified, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE_URL}/distribution-journaux-municipaux`, lastModified, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE_URL}/distribution-tracts-municipaux`, lastModified, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${BASE_URL}/distribution-flyers-paris`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-boulogne-billancourt`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-saint-denis`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-argenteuil`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-nanterre`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-montreuil`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-bordeaux`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-toulouse`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-marseille`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-lille`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-strasbourg`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-metz`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-mulhouse`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-nancy`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-rennes`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-reims`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-saint-etienne`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-le-havre`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-angers`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-toulon`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-lyon`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-grenoble`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-clermont-ferrand`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-annecy`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-valence`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-dijon`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-nice`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-nantes`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-montpellier`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-nimes`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-pau`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-perpignan`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-beziers`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-albi`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-brest`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-aix-en-provence`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-colmar`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-quimper`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-lorient`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-vannes`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-saint-brieuc`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-orleans`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-tours`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-bourges`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-blois`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-chateauroux`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-chartres`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-limoges`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-poitiers`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-la-rochelle`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-bayonne`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-le-mans`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-saint-nazaire`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-laval`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-cholet`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-rouen`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-caen`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-cherbourg-en-cotentin`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-evreux`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/distribution-flyers-dieppe`, lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE_URL}/politique-de-confidentialite`, lastModified, changeFrequency: 'yearly', priority: 0.3 },
    { url: `${BASE_URL}/politique-de-cookies`, lastModified, changeFrequency: 'yearly', priority: 0.3 },
    { url: `${BASE_URL}/conditions-d-utilisation`, lastModified, changeFrequency: 'yearly', priority: 0.3 },
  ]

  return routes
}
